### PR TITLE
Support python 3.11 and update dependencies

### PR DESCRIPTION
**Pull request by ttys0dev**
Lets test on python 3.11.

### CODE REVIEW

**Comment by mlissner** [comment]
Great idea, thanks. Looks like it's failing no less.

**Comment by ttys0dev** [comment]
> Looks like it's failing no less.

Yeah...looks like dev deps needed to be updated, tests fixed.

**Comment by ttys0dev** [comment]
@mlissner does this look good to merge?

**Comment by mlissner** [comment]
Looks good, thanks.

**Comment by ttys0dev** [comment]
@mlissner Want to spin a new release now that python 3.11 is supported?

**Comment by mlissner** [comment]
Sure, when https://github.com/freelawproject/eyecite/pull/152 is merged, a new release should be automatic.

**Pull request merged**
