### PR TITLE
version bump v2.6.0

### PR DESCRIPTION
**Pull request by ERosendo**

### CODE REVIEW

**Comment by ERosendo** [comment]
@mlissner While the `Pdoc` action is now working correctly, the `PyPI` action is unfortunately failing. It appears that one of the updates within this PR may have triggered a release. The new version can be found here: https://pypi.org/project/eyecite/ 

I've verified that the published `.tar` file includes the changes listed in the `CHANGES.md` file, and the `pyproject.toml` file also reflects the correct version. Based on this, I believe it's safe to merge this PR.

**Comment by mlissner** [comment]
Great, thanks.

**Comment by mattdahl** [comment]
Just circling back to this, I see on pypi that 2.6.0 has been released, but 2.5.3, 2.5.4, and 2.5.5 have not been yanked yet.

**Comment by mlissner** [comment]
Oops, sorry, thanks for the reminder. Those versions are now yanked, so I think now we get to see what kind of fallout we incur (hopefully none?).

**Pull request merged**
