### PR TITLE
Issue 137 - Fix Hyperscan duplicate editions bug

### PR DESCRIPTION
**Pull request by mattdahl**
Bug is described in #137. In theory, I think this could affect other tokenizers too, but I only see the problem in `HyperscanTokenizer`. My proposed solution is simple -- just remove duplicate candidate editions after citation tokens are merged. If there is some reason why those duplicates should be retained, I'm missing it.

### CODE REVIEW

**Comment by mlissner** [comment]
Seems simple enough, but a number of tests are failing. Any idea what's going on there?

**Comment by mattdahl** [comment]
Not sure what the problem is, they all passed fine on my fork (same commit hash): https://github.com/mattdahl/eyecite/actions/runs/3962150256/. Also not sure why the dependencies (`fast_diff_match_patch`, `exrex`) don't load on only some Python versions.

**Comment by flooie** [comment]
@mattdahl @mlissner - it certainly doesn't appear to be related to your PR.  I re-ran tests for python 3.8 for a branch that passed tests yesterday (I think) to see if it would happen on it now fails.  So somewhere downstream something has changed.

**Comment by mattdahl** [comment]
Can this be reviewed/merged now that #140 has fixed the CI problem? (Though note that now another CI problem will need to be fixed first in #143)

**Comment by mlissner** [comment]
I synced with main and tests are re-running. If they pass, we'll be in business, I think.

**Comment by mlissner** [comment]
Thanks for bumping this Matt! Merged!

**Pull request merged**
