### PR TITLE
test and fix for issue #167

### PR DESCRIPTION
**Pull request by cbrew**
Hash function did not handle datetime and failed.

### CODE REVIEW

**Comment by mlissner** [comment]
Looks like we've got issues with our build unrelated to this PR. @cbrew, do I guess correctly that you'd rather not go down this rabbit hole? If so, I can ask somebody on our staff to do so, or it's possible @mattdahl might be game.

**Comment by mlissner** [comment]
Fair enough. @cbrew, what do you think?

**Comment by cbrew** [comment]
I don’t think Lexis would thank me for spending the time. I was game if it
was going to take only a little time.  So if someone can take it, great.

I’m interested in finding out how far new tech can take us in delimiting
the borders of the citing language, either with or without assumptions
about which passage the citation is pointing to. The chance of having both
ends of the graph edge visible in pile of law goes up fast as its coverage
increases. Having your tool as an experimental tool is a delight.

**Comment by mlissner** [comment]
No worries! One of our devs fixed the testing problem (hopefully). 

Now the only issue is that your code isn't passing the linting rule for a very minor reason. Mind fixing that and then we'll be good to go?

**Comment by cbrew** [comment]
still getting a mystery error about "resource not accessible ny integration'

**Comment by mlissner** [comment]
@ERosendo can you take another look at getting this one over the hump, please? 

Thanks Chris!

**Comment by ERosendo** [comment]
@mlissner I've updated this PR and I've made some minor code changes to avoid unnecessary updates to the poetry.lock file. All tests are passing and the linting check is successful.

I believe the current issue with the **Benchmark Pull Request check** is related to token permissions. Workflows triggered by pull requests from **forked repositories** use a `read-only` token and all other secrets are not available to the workflow run. This means any attempts to write, such as creating comments on the pull request using `GITHUB_TOKEN` or other secrets, will fail.

**Comment by mlissner** [comment]
Excellent, thank you, merging!

**Pull request merged**
